sudo: required
language: cpp

matrix:
  include:
    # Ubuntu 14.04 Trusty
    - {os: "linux", dist: "trusty",  env: "QT5_BUILD=ON",   compiler: "gcc"}
    - {os: "linux", dist: "trusty",  env: "QT5_BUILD=OFF",  compiler: "gcc"}
    # Ubuntu 16.04 Xenial
    - {os: "linux", dist: "xenial",  env: "QT5_BUILD=ON",   compiler: "gcc"}
    - {os: "linux", dist: "xenial",  env: "QT5_BUILD=OFF",  compiler: "gcc"}
    # macOS
    - {os: "osx", compiler: "clang"}

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
            -DCMAKE_BUILD_TYPE=Debug
            -DQT5_BUILD=$QT5_BUILD
            . && make;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_PREFIX_PATH=$(brew cask info sparkle | grep /usr/local/Caskroom | cut -d' ' -f 1)\;$(brew --prefix qt5)
            . && make;
    fi

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$QT5_BUILD" == "ON" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qtbase5-dev qttools5-dev qttools5-dev-tools; fi
  - if [[ "$QT5_BUILD" == "OFF" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libqt4-dev libqjson-dev; fi
  - if [[ "$CXX" == "clang++" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [[ "$CXX" == "g++" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install sparkle; fi
